CREATE TABLE ENROLLMENT (
  -> PSSN numeric(9),
  -> SCWID numeric(9),
  -> DNO numeric(5),
  -> CNO numeric(5),
  -> SNO numeric(2),
  -> Grade char(2),
  -> PRIMARY KEY (PSSN, SCWID, DNO, CNO, SNO),
  -> FOREIGN KEY (PSSN) REFERENCES PROFESSOR(SSN),
  -> FOREIGN KEY (SCWID) REFERENCES STUDENT(CWID),
  -> FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNumber),
  -> FOREIGN KEY (CNO) REFERENCES COURSE(CNumber),
  -> FOREIGN KEY (SNO) REFERENCES SECTION(SNumber)
);
